branch-defaults:
  master:
    environment: short-urls-prod
global:
  application_name: short_urls
  default_ec2_keyname: null
  default_platform: Docker 18.06.1-ce
  default_region: us-east-1
  sc: git
